# Generated by Django 5.2 on 2026-01-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='token',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
