# Generated by Django 5.2 on 2026-02-04 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='plan',
        ),
    ]
