# Generated by Django 5.2 on 2026-01-24 14:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0002_userinfo_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
