# Generated by Django 5.2 on 2026-02-04 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0003_remove_userinfo_plan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': '用户管理', 'verbose_name_plural': '用户管理'},
        ),
    ]
