server {
    listen 80; # 监听端口
    server_name localhost 127.0.0.1; # 域名

    root /app/; # 网页路径
    index egg.html index.htm; # 索引首页文件（默认index.html）
    # error_page 404 /404.html # 404错误页面

    # url匹配然后走反向代理
    location / {
        proxy_pass http://localhost:8000;
    }

    location /static/ {
        alias /app/staticfiles/;
    }
}