# Generated by Django 5.2 on 2026-01-23 02:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='套餐名')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='套餐介绍')),
                ('points', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='点数')),
            ],
            options={
                'verbose_name': '套餐信息',
                'verbose_name_plural': '套餐信息',
                'db_table': 'plan',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='项目名')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
            ],
            options={
                'verbose_name': '项目信息',
                'verbose_name_plural': '项目信息',
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='接口名')),
                ('point', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='所需点数')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apis', to='dashboard.project', verbose_name='项目名')),
            ],
            options={
                'verbose_name': '接口信息',
                'verbose_name_plural': '接口信息',
                'db_table': 'api',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='点数')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_info', to='dashboard.plan', verbose_name='套餐名')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户管理',
                'verbose_name_plural': '用户管理',
                'db_table': 'user_info',
            },
        ),
    ]
