# Generated by Django 5.2 on 2026-01-23 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_userinfo_options_alter_plan_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='projects_icon', verbose_name='上传图标'),
        ),
    ]
