# Generated by Django 5.2 on 2026-01-24 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_project_icon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
