# Generated by Django 5.2 on 2026-01-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_delete_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='description',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='接口介绍'),
        ),
    ]
