# Generated by Django 5.2 on 2026-01-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_api_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='api_path',
            field=models.CharField(default='/', max_length=50, verbose_name='接口路径'),
        ),
    ]
