# Generated by Django 5.2 on 2026-01-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_api_api_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='data',
            field=models.TextField(blank=True, null=True, verbose_name='请求体'),
        ),
        migrations.AddField(
            model_name='api',
            name='method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], default='GET', max_length=10, verbose_name='请求方法'),
        ),
        migrations.AddField(
            model_name='api',
            name='res_data',
            field=models.TextField(default='', verbose_name='响应体'),
        ),
    ]
