# Generated by Django 5.2 on 2026-01-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_api_data_api_method_api_res_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api',
            name='data',
        ),
        migrations.AddField(
            model_name='api',
            name='req_data',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='请求体'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='项目名'),
        ),
    ]
