# Generated by Django 5.2 on 2026-01-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_api_data_api_req_data_alter_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='req_data',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='请求体'),
        ),
    ]
