# Generated by Django 5.2 on 2026-01-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_api_req_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='req_data',
            field=models.TextField(blank=True, default='', null=True, verbose_name='请求体'),
        ),
    ]
