# Generated by Django 5.2 on 2026-01-24 08:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_api_req_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='价格'),
        ),
    ]
