# Generated by Django 5.2 on 2026-01-24 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_plan_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='description',
        ),
    ]
