# Generated by Django 5.2 on 2026-01-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_remove_plan_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='api_path',
            field=models.CharField(default='http://example.com', max_length=50, verbose_name='接口URL'),
        ),
    ]
