# Generated by Django 5.2 on 2026-01-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_api_api_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='icon',
        ),
        migrations.AlterField(
            model_name='api',
            name='api_path',
            field=models.CharField(default='/', max_length=50, verbose_name='接口URL'),
        ),
    ]
