# Generated by Django 5.2 on 2026-01-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_remove_project_icon_alter_api_api_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='api_path',
            field=models.CharField(default='/items/', max_length=50, verbose_name='接口URL'),
        ),
    ]
