# Generated by Django 5.2 on 2026-01-24 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_api_api_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api',
            name='api_path',
        ),
    ]
