# Generated by Django 5.2 on 2026-01-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_remove_api_api_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='res_data',
            field=models.TextField(verbose_name='响应体'),
        ),
    ]
