# Generated by Django 5.2 on 2026-01-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_alter_api_res_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='is_show',
            field=models.BooleanField(default=True, verbose_name='显示'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_show',
            field=models.BooleanField(default=True, verbose_name='显示'),
        ),
    ]
