# Generated by Django 5.2 on 2026-02-04 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='docs',
            options={'verbose_name': '文档管理', 'verbose_name_plural': '文档管理'},
        ),
    ]
