"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import secrets
from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = config('DEBUG', cast=bool)
SECRET_KEY = config('SECRET_KEY', default=secrets.token_hex(32))

ALLOWED_HOSTS = config(
    'ALLOWED_HOSTS',
    default='',  # 开发环境默认值
    cast=lambda v: [s.strip() for s in v.split(',')]  # 转换为列表
)
# ========== 补充IPv6支持 ==========
ALLOWED_HOSTS += ['[::1]']
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='',
                              cast=lambda v: [s.strip() for s in v.split(',')])

# ========== 基础安全配置（所有环境通用） ==========
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'SAMEORIGIN' if DEBUG else 'DENY'
USE_X_FORWARDED_HOST = not DEBUG  # 生产环境用Nginx的Host头
USE_X_FORWARDED_PORT = not DEBUG  # 让Django解析Nginx的443端口
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')  # 全局配置，HTTPS固定值


if DEBUG:
    # 开发环境：禁用所有HTTPS相关安全检查，消除警告
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_HSTS_SECONDS = 0  # 完全禁用HSTS
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False

    # 静默HTTPS相关警告
    SILENCED_SYSTEM_CHECKS = [
        'security.W004',  # HSTS
        'security.W008',  # SSL重定向
        'security.W012',  # Session Cookie安全
        'security.W016',  # CSRF Cookie安全
    ]

else:
    # 生产环境
    SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', cast=bool)
    # 开启HTTPS相关安全配置
    SESSION_COOKIE_SECURE = True  # Session Cookie仅在HTTPS下传输
    CSRF_COOKIE_SECURE = True    # CSRF Cookie仅在HTTPS下传输
    SECURE_HSTS_SECONDS = 31536000  # HSTS有效期1年
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True  # 包含子域名
    SECURE_HSTS_PRELOAD = True  # 加入浏览器HSTS预加载列表


# Application definition

INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'order',
    'view',
    'my_auth'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'builtins':['django.templatetags.static']
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': config('ENGINE'),
        'NAME': config('MYSQL_DATABASE'),
        'USER': config('MYSQL_USER', 'root'),
        'PASSWORD': config('MYSQL_ROOT_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

# 语言与时间
LANGUAGE_CODE = 'zh-hans'
TIME_ZONE = 'Asia/Shanghai'

# 国际化支持
USE_I18N = True

USE_TZ = True

LOGIN_URL = '/auth/login'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/' # 访问静态文件URL
STATICFILES_DIRS = [BASE_DIR / "static"] # 开发时查找静态文件的目录列表
STATIC_ROOT = BASE_DIR / 'staticfiles'

# MEDIA_URL = 'media/'  # 访问媒体文件的URL
# MEDIA_ROOT = BASE_DIR / 'media'  # 存储上传文件的位置

#### 支付宝 ####
ZFB_SERVER_URL = config('ZFB_SERVER_URL')
ZFB_APPID = config('ZFB_APPID', cast=str)
ZFB_SELLER_ID = config('ZFB_SELLER_ID', cast=str)
ZFB_PUBLIC_KEY = config('ZFB_PUBLIC_KEY')
ZFB_APP_PRIVATE_KEY = config('ZFB_APP_PRIVATE_KEY')
ZFB_RETURN_URL = config('ZFB_RETURN_URL')
ZFB_NOTIFY_URL = config('ZFB_NOTIFY_URL')