# Generated by Django 5.2 on 2026-02-04 05:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('my_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='套餐名')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='价格')),
                ('points', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='点数')),
            ],
            options={
                'verbose_name': '套餐信息',
                'verbose_name_plural': '套餐信息',
                'db_table': 'plan',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='项目名')),
                ('is_show', models.BooleanField(default=True, verbose_name='显示')),
            ],
            options={
                'verbose_name': '项目信息',
                'verbose_name_plural': '项目信息',
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_sn', models.CharField(max_length=100, unique=True, verbose_name='系统订单编号')),
                ('pay_type', models.CharField(choices=[('alipay', '支付宝'), ('wxpay', '微信')], max_length=10, verbose_name='支付方式')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('state', models.BooleanField(choices=[(False, '未支付'), (True, '已支付')], default=False, verbose_name='支付状态')),
                ('trade_no', models.CharField(max_length=100, verbose_name='支付订单编号')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='支付金额')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_auth.userinfo', verbose_name='下单用户')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.plan', verbose_name='套餐')),
            ],
            options={
                'verbose_name': '订单信息',
                'verbose_name_plural': '订单信息',
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='接口名')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], default='GET', max_length=10, verbose_name='请求方法')),
                ('req_data', models.TextField(blank=True, default='', null=True, verbose_name='请求体')),
                ('res_data', models.TextField(verbose_name='响应体')),
                ('description', models.TextField(blank=True, max_length=100, null=True, verbose_name='接口介绍')),
                ('point', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='所需点数')),
                ('is_show', models.BooleanField(default=True, verbose_name='显示')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apis', to='order.project', verbose_name='项目名')),
            ],
            options={
                'verbose_name': '接口信息',
                'verbose_name_plural': '接口信息',
                'db_table': 'api',
            },
        ),
    ]
