# Generated by Django 5.2 on 2026-02-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='api',
            options={'verbose_name': '接口管理', 'verbose_name_plural': '接口管理'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '订单管理', 'verbose_name_plural': '订单管理'},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name': '套餐管理', 'verbose_name_plural': '套餐管理'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': '项目管理', 'verbose_name_plural': '项目管理'},
        ),
        migrations.AlterField(
            model_name='api',
            name='is_show',
            field=models.BooleanField(default=True, verbose_name='显示状态'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_show',
            field=models.BooleanField(default=True, verbose_name='显示状态'),
        ),
    ]
